### PR TITLE
Updated voku/stringy

### PR DESCRIPTION
**Pull request by kerns**
Updated voku/stringy for Craft 3.5 to ^6.2.2

### CODE REVIEW

**Comment by philipzaengle** [comment]
Can confirm this resolves the issue

**Comment by michaelrog** [comment]
As far as I know, a [caret version range](https://getcomposer.org/doc/articles/versions.md#caret-version-range-) always allows non-breaking updates within a major version, so `^6.0` and `^6.2.2` are functionally equivalent.

@kerns, @philipzaengle — Could you make sure your dependency constraint for Wordsmith allows the latest version (3.3.0) to be installed, and let me know if the issue persists then?

(Wordsmith 3.3 uses a later version of Stringy in order to be compatible with Craft 3.5, so you should be able to update both in tandem. Versions of Wordsmith prior to 3.3 will not be compatible with Craft 3.5.)

**Comment by michaelrog** [comment]
p.s. If yall are installing via the Plugin Store (as opposed to using Composer directly), this info will be useful:

https://github.com/TopShelfCraft/Wordsmith/issues/37

**Comment by kerns** [comment]
I personally resolved the issue by uninstalling and removing the plug-in and then reinstalling after updating to 3.5. 👌

**Comment by philipzaengle** [comment]
We had originally installed via the plugin store -- uninstalling and reinstalling the plugin did the trick. booyah! 

Thanks, @michaelrog !

**Pull request closed without merging**
